version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  myjob1:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudfomration Stack
          command: |
            aws cloudformation deploy \
              --template-file CloudFormation/template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region eu-west-2
workflows:
  myWorkflow:
    jobs:
      - create_infrastructure
