version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  create_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["1e:3d:96:35:ce:53:25:b9:b7:97:54:11:e6:44:1f:f0"]
      - run:
          name: Install Ansible
          command: |
            apt-get update -y
            apt install ansible -y
            which ansible
      - run:
          name: Run Playbook and Configure Server
          command: |
            ansible-playbook -i inventory.txt main.yml
workflows:
  myWorkflow:
    jobs:
      - create_infrastructure
